CREATE USER school_settings WITH PASSWORD 'school_settings';
CREATE USER school_subscription WITH PASSWORD 'school_subscription';
CREATE USER school_forms WITH PASSWORD 'school_forms';
CREATE USER school_workflow WITH PASSWORD 'school_workflow';
CREATE USER school_rules WITH PASSWORD 'school_rules';
CREATE USER school_reports WITH PASSWORD 'school_reports';
CREATE USER school_notif_cfg WITH PASSWORD 'school_notif_cfg';
CREATE USER school_audit WITH PASSWORD 'school_audit';
CREATE USER school_admission WITH PASSWORD 'school_admission';
CREATE USER school_fee WITH PASSWORD 'school_fee';
CREATE USER school_student WITH PASSWORD 'school_student';
CREATE USER school_attendance WITH PASSWORD 'school_attendance';
CREATE USER school_exam WITH PASSWORD 'school_exam';
CREATE USER school_library WITH PASSWORD 'school_library';
CREATE USER school_hostel WITH PASSWORD 'school_hostel';
CREATE USER school_transport WITH PASSWORD 'school_transport';
CREATE USER school_payroll WITH PASSWORD 'school_payroll';
CREATE USER school_staff WITH PASSWORD 'school_staff';
CREATE USER school_academic WITH PASSWORD 'school_academic';
CREATE USER school_website WITH PASSWORD 'school_website';
CREATE USER school_cms WITH PASSWORD 'school_cms';

CREATE DATABASE school_settings_db OWNER school_settings;
CREATE DATABASE school_subscription_db OWNER school_subscription;
CREATE DATABASE school_forms_db OWNER school_forms;
CREATE DATABASE school_workflow_db OWNER school_workflow;
CREATE DATABASE school_rules_db OWNER school_rules;
CREATE DATABASE school_reports_db OWNER school_reports;
CREATE DATABASE school_notif_cfg_db OWNER school_notif_cfg;
CREATE DATABASE school_audit_db OWNER school_audit;
CREATE DATABASE school_admission_db OWNER school_admission;
CREATE DATABASE school_fee_db OWNER school_fee;
CREATE DATABASE school_student_db OWNER school_student;
CREATE DATABASE school_attendance_db OWNER school_attendance;
CREATE DATABASE school_exam_db OWNER school_exam;
CREATE DATABASE school_library_db OWNER school_library;
CREATE DATABASE school_hostel_db OWNER school_hostel;
CREATE DATABASE school_transport_db OWNER school_transport;
CREATE DATABASE school_payroll_db OWNER school_payroll;
CREATE DATABASE school_staff_db OWNER school_staff;
CREATE DATABASE school_academic_db OWNER school_academic;
CREATE DATABASE school_website_db OWNER school_website;
CREATE DATABASE school_cms_db OWNER school_cms;